deploy_user: deployer
deploy_user_shell: /bin/bash
deploy_user_groups: www-data
web_root: /var/www/html
php_packages:
  - php
  - php-mysql
  - php-cli
  - php-curl
  - php-mbstring
  - libapache2-mod-php
base_packages:
  - apache2
  - mysql-server
  - ufw
  - git
  - curl
  - unzip
ufw_allowed_ports:
  - "22"
  - "80"
  - "443"
app_page_title: "TCC - Infraestrutura como Código"
app_server_name: "{{ inventory_hostname }}"
